### ISSUE TITLE
Donation box 💰

### ISSUE THREAD

**Issue by MartaSien** [hs3city/hs3-laser-cut#1]
**Task**
Create a design for a donation box for Hackerspace Trójmiasto.

**Design features**
- [ ] size around 40x40x30 cm
- [ ] [Gridfinity compatible](https://github.com/hs3city/hs3-laser-cut/wiki/Gridfinity-compatible-design)
- [ ] transparent front
- [ ] sides from plexi or wood
- [ ] lockable
